# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: baa6e93204ae547837f534911b2fcee5bf0802c92d5d006824e4a01a492e9d33ef3fdd792bf14a7b4e0aef4176b4b2e2961006a3d7ca30e9c7c00a5d7bfa3776

test:
  secret_key_base: e61ed62a1deda4b3de175e6b0c4a6b945065a98e0e7a1d7abd4b06f6a3a64be1db60c2897878e8f487f824bb252d3efd7ccf13c277ba27bbd70376a5aa0de05e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
